version: '2'
services:
  back:
    container_name: back
    build: 
      context: .
      dockerfile: ./docker/back/Dockerfile
    volumes:
      - ./back/src:/usr/src/app
    ports:
      - "8080:8080"

  front:
    container_name: front
    build: 
      context: .
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "80:80"
    

    