version: '2'
services:
  web:
    container_name: node_test
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./back/src:/usr/src/app
    ports:
      - "8080:8080"
    